### ISSUE TITLE
How to configure horizontal auto scaler?

### ISSUE THREAD

**Issue by glundgrenm** [cuber-cloud/cuber-gem#14]
Hello! First of all, thanks for this awesome tool.

I was wondering if it's possible to configure the horizontal auto scaler (i am using Google Cloud Kubernetes) within the cuber deploy file.

Is it possible? Can you give me some advice on that topic?

Thanks a lot!

**Comment by collimarco** [comment]
Hello,

The current version of Cuber does not support autoscaling: you need to manually change the proc `scale` in the Cuberfile to the desired number of replicas and then run `cuber deploy`. This has proved to be simple and effective for our use case.

Feel free to open a pull request if you decide to implement the autoscaling feature (e.g. `proc :example,  scale: 3 .. 5`). Please note that any solution must be compatible with all cloud providers (so it should not use features that are specific to Google Cloud).
