### ISSUE TITLE
The registry read access problem.

### ISSUE THREAD

**Issue by szluyufeng** [cuber-cloud/cuber-gem#4]
When I cuber deploy, I got this: 

```
Cloning Git repository
正克隆到 '.cuber/repo'...
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 94 (delta 2), reused 92 (delta 2), pack-reused 0
接收对象中: 100% (94/94), 42.71 KiB | 247.00 KiB/s, 完成.
处理 delta 中: 100% (2/2), 完成.

-----> Building image using buildpacks
20: Pulling from heroku/buildpacks
Digest: sha256:08688e88e6e0debc7f4df556fd2d5a71fee1ab501715ae1f54b9792e9f7708a1
Status: Image is up to date for heroku/buildpacks:20
ERROR: failed to : ensure registry read access to linusef/docker-demo:2a63d19-20220624174615
ERROR: failed to build: executing lifecycle: failed with status code: 1
Cuber: pack build failed
```

I spent whole night to figure it out, but failed. Can't find a solution. 😂
This is a really cool deploy tool, better than kuby, but maybe we need a more detailed document.

**Comment by collimarco** [comment]
Hello @szluyufeng,

Thanks for reporting this issue.

The output that you see is from the `pack` command (it is a tool developed by CNCF and Heroku: https://buildpacks.io).

Cuber is just invoking the `pack` command there and that error does not seem related to Cuber: can you please report the issue here? 

https://github.com/buildpacks/pack/issues

Please let me know and feel free to reference this discussion when you open the issue in the other repo.

**Comment by szluyufeng** [comment]
OK, Thanks. I'll make more research on it.

Is there any problem with my Cuberfile? I've tried many versions.

```
app 'docker-demo'
repo 'https://github.com/szluyufeng/docker-demo.git'
buildpacks 'heroku/buildpacks:20'
image 'linusef/docker-demo'
dockerconfig 'dockerconfig.json'
kubeconfig 'kubeconfig.yml'
proc :web, 'bundle exec puma', scale: 4
cache false

env 'RAILS_ENV', 'production'
env 'RAILS_MASTER_KEY', File.read('config/master.key'), secret: true

# Migrations
migrate 'rails db:migrate'
```

```
{
  "auths": {
    "https://index.docker.io/v1/": {
      "Username": "linusef",
      "Secret": "my_token"
  }
}
```

**Comment by collimarco** [comment]
```
image 'linusef/docker-demo'
```

I see now that `linusef/docker-demo` is the name of your personal repo... So probably the error above, raised by `pack`, means that **you don't have access to that Docker repository or that it doesn't exist**.

If you try a normal `docker push` of any image to that Docker repo, does it work?

Please note that in the current version of Cuber the `dockerconfig 'dockerconfig.json'` is only used by Kubernetes... Your local machine needs to have access to the Docker repo. i.e. the docker build / docker push do not read that `dockerconfig` file, but the general configuration of Docker on your local machine.

```
migrate 'rails db:migrate'
```

A complete example of `Cuberfile` for Rails is available here:

https://discuss.rubyonrails.org/t/cuber-a-new-simple-way-to-deploy-rails-apps/80156

**Comment by szluyufeng** [comment]
`docker push` is working fine. Still can't figure out the problem, it's wired. 😂
I need more DOCKER knowledge.
Really appreciate your answer. If I can fix this I will post it here.

**Comment by collimarco** [comment]
@szluyufeng I made a quick search and I find this post on StackOverflow with the same error:

https://stackoverflow.com/a/71628784/51387

Point (1) is the solution in my opinion... As I already said **you first need to login to Docker using `docker login`** or the Docker Desktop UI.

Point (2) can be ignored in our case, since Cuber automatically adds the tag to the image for you.

**Comment by szluyufeng** [comment]
@collimarco Yes, `docker login` works, and so does `docker push`. I think you are right, it's a `buildpack` issue.

**Comment by collimarco** [comment]
@szluyufeng Nice to see that you have solved this issue. What was the problem? If you can share your solution maybe it can be useful for others in the future.

**Comment by szluyufeng** [comment]
@collimarco Sorry for the late reply, I just saw this. I never solved the issue(which I really want). Finally I got back to the old solution, deploying with capistrano. But I am still interested in Cuber, and will put much more effort to make it running in the future. Cuber is really a good and simplest solution for k8s.
